# Generated by Django 5.0.1 on 2024-02-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=65)),
                ('descricao', models.CharField(max_length=200)),
                ('paginas', models.IntegerField()),
                ('autor', models.CharField(max_length=50)),
                ('emprestado', models.BooleanField(verbose_name='')),
            ],
        ),
    ]
