# Generated by Django 5.0.1 on 2024-02-19 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_alter_livro_options_livro_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={},
        ),
        migrations.AddField(
            model_name='livro',
            name='cover',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='livros/covers/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
