# Generated by Django 5.0.1 on 2024-02-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_alter_livro_options_livro_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
