# Generated by Django 5.0.1 on 2024-03-06 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0008_livro_usuario_emprestimo'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='usuario_emprestimo',
        ),
        migrations.AddField(
            model_name='livro',
            name='emprestado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario'),
        ),
    ]
