# Generated by Django 5.0 on 2024-07-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0009_remove_livro_usuario_emprestimo_livro_emprestado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
