# Generated by Django 5.0 on 2024-07-21 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0010_alter_livro_data_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='tempo_duracao',
        ),
    ]
