# Generated by Django 5.0 on 2024-07-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0011_remove_livro_tempo_duracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='arquivo_livro',
            field=models.FileField(blank=True, null=True, upload_to='livros/arquivos/%Y/%m/%d/'),
        ),
    ]
