# Generated by Django 6.0.1 on 2026-01-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0012_livro_arquivo_livro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='arquivo_livro',
        ),
        migrations.AddField(
            model_name='livro',
            name='deletado',
            field=models.BooleanField(default=False),
        ),
    ]
