# Generated by Django 6.0.1 on 2026-01-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0013_remove_livro_arquivo_livro_livro_deletado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='descricao',
            field=models.CharField(blank=True, null=True),
        ),
    ]
