# Generated by Django 6.0.1 on 2026-01-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0016_alter_avaliacao_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='deletado',
            field=models.BooleanField(default=False),
        ),
    ]
