# Generated by Django 6.0.1 on 2026-01-23 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0017_avaliacao_deletado'),
        ('usuario', '0004_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='denuncias_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Denuncias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('SPAM', 'Conteúdo inadequado'), ('OFENSIVO', 'Linguagem ofensiva'), ('FALSO', 'Informação falsa'), ('OUTRO', 'Outro motivo')], verbose_name='')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.avaliacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
