# Generated by Django 6.0.1 on 2026-01-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0018_avaliacao_denuncias_count_denuncias'),
        ('usuario', '0004_alter_usuario_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Denuncias',
            new_name='Denuncia',
        ),
    ]
