# Generated by Django 6.0.1 on 2026-01-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0019_rename_denuncias_denuncia'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='deletada',
            field=models.BooleanField(default=False),
        ),
    ]
