# Generated by Django 6.0.1 on 2026-01-26 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0020_denuncia_deletada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='deletada',
        ),
    ]
