# Generated by Django 5.0 on 2024-07-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Usuario_comum', 'Usuario_comum')], default='Usuario_comum', max_length=13),
        ),
    ]
